# ==========================================
# pytest.ini - Pytest Configuration File
# ==========================================

[pytest]

testpaths = tests/ui

addopts =
    # ------------------------------
    # General Options
    # ------------------------------
    -v
    --browser=chromium
    ; --headed
    --base-url=https://tutorialsninja.com/demo/

    # ------------------------------
    # Captures and Reports (Debugging)
    # ------------------------------
    --video=retain-on-failure
    --screenshot=only-on-failure
    --tracing=retain-on-failure
    --html=reports/myreport.html
    --self-contained-html
    --capture=tee-sys
    --alluredir=reports/allure-results
    --junitxml=reports/results.xml

    # ------------------------------
    # Parallel Execution
    # ------------------------------
    #-n=1
    #--numprocesses=2

    # ------------------------------
    # Test Grouping (Markers)
    # ------------------------------
    ; -m "sanity"
    # -m "regression"
    # -m "sanity or regression"

    # ------------------------------
    # Flaky Test Handling
    # ------------------------------
    ; --reruns 2
    ; --reruns-delay 2


# ------------------------------
# Custom Markers
# ------------------------------
markers =
    sanity: marks a sanity test (basic quick check)
    regression: marks a regression test (full end-to-end validation)
    datadriven: marks a datadriven test
    end_to_end: marks an end-to-end test
    api: marks an API test
    smoke: marks a smoke test
    ui: marks a UI test
    bug: marks a test as having a known bug